### ISSUE TITLE
Accessibility remarks by Andrea Fercia

### ISSUE THREAD

**Issue by giancarlomosso** [ThomasVitale/wctrn-2017#1]
importanti (andrebbero sistemate):
1) menu di navigazione: non è possibile espandere i sotto menu e accedere ai sub menu items utilizzando solo la tastiera. Per Milano avevamo utilizzato Twenty Sixteen come tema base e il menu funziona. Invece, non so se il tema `wordcamp-base` può essere modificato per sistemare il menu
2) links all'interno di blocchi di testo devono avere underline, altrimenti chi non percepisce bene i colori non può capire che si tratta di links (vedi screenshot) 
3) headings vuoti, esempio:
    `<h3 class="divider"></h3>`
4) alcune immagini non hanno un attributo alt (se sono solo decorative dovrebbero avere almeno alt=""), esempio: salvadanaio porcellino
5) contrasto colori form modulo contatti, form call for sponsors (altri?) (vedi screenshot)

6) altri contrasti colori, se si ha il tempo...:
    sub menu items on hover white su #0093b2
    link TICKET in alto a destra white su #c55a5b
    link next/previous #00697f su #bedae2 (controllare anche on hover/focus)
    (bisognerebbe controllare tutti i contrasti, qui ho menzionato solo quelli che mi sembravano più evidenti a una veloce visita sul sito)

7) id duplicate, esempio in home page:
```
<h3 id="en610" class="divider">English</h3>
<h3 id="en610" class="divider">English</h3>
```
8) le widget twitter e facebook sono un disastro ma lì temo non si possa fare molto

![image](https://cloud.githubusercontent.com/assets/24539575/23094216/2d27080c-f5f5-11e6-811e-02a3e144b208.png)

![image](https://cloud.githubusercontent.com/assets/24539575/23094263/a627eec4-f5f5-11e6-92b0-dade67e82a18.png)

**Comment by ThomasVitale** [comment]
PUNTO 1

Purtroppo non può essere risolto, il tema in uso non prevede la possibilità di accedere ai sub menu.

**Comment by ThomasVitale** [comment]
PUNTO 5

Risolto

**Comment by ThomasVitale** [comment]
PUNTO 8

Non abbiamo controllo su questi componenti esterni purtroppo.

**Comment by ThomasVitale** [comment]
PUNTO 3 e PUNTO 7

Revisionati tutti i post pubblicati e corretti quelli che non rispettavano le linee guida fornite per l'aggiunta del testo in doppia lingua.

**Comment by ThomasVitale** [comment]
PUNTO 2

Risolto

**Comment by ThomasVitale** [comment]
PUNTO 4

Segnalato a tutti i team che si occupano di contenuti.

**Comment by ThomasVitale** [comment]
PUNTO 6

Risolto
